### PR TITLE
Skip paths matching the paths in .gitignore

### PR DESCRIPTION
**Pull request by mizzy**
First, thanks to the very useful tool you developed.

I'd like to dirmap not showing the paths that matches the paths in .gitignore.

So I added the function to skip the paths matching the paths in .gitignore.

Please check it.

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @mizzy 

> I'd like to dirmap not showing the paths that matches the paths in .gitignore.

!!!

This is an idea I hadn't thought of at all. I thought it was very great!!!

**Comment by k1LoW** [comment]
Looks like you need to add go.mod and go.sum, but I'll add them.

Thanks for the nice feature!

**Comment by mizzy** [comment]
> Looks like you need to add go.mod and go.sum, but I'll add them.

Sorry, I forgot to commit and push them.

Thanks to adding them and merging my PR!

**Comment by k1LoW** [comment]
Released as [v0.2.0](https://github.com/k1LoW/dirmap/releases/tag/v0.2.0).

**Pull request merged**
